# Generated by Django 3.1.5 on 2021-04-06 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dprocess', '0004_auto_20210404_0245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='UpdateOrder',
        ),
    ]
