# Generated by Django 3.1.5 on 2021-03-27 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210327_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default='For Chronological Order')),
                ('email_address_0', models.EmailField(blank=True, max_length=60, null=True, verbose_name='email')),
                ('email_address_1', models.EmailField(blank=True, max_length=60, null=True, verbose_name='email')),
                ('facebook_handler', models.URLField(blank=True, null=True)),
                ('twitter_handler', models.URLField(blank=True, null=True)),
                ('instagram_handler', models.URLField(blank=True, null=True)),
                ('linkedin_handler', models.URLField(blank=True, null=True)),
                ('phone_number', models.IntegerField(default='1234567890', validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('use', models.BooleanField(default=False)),
            ],
        ),
    ]
