# Generated by Django 3.1.5 on 2021-03-24 11:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210305_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 11, 40, 35, 29281, tzinfo=utc)),
        ),
    ]
