# Generated by Django 3.1.5 on 2021-03-24 11:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210324_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 11, 52, 50, 520661, tzinfo=utc)),
        ),
    ]
