# Generated by Django 3.1.5 on 2021-03-24 12:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210324_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 12, 36, 23, 105613, tzinfo=utc)),
        ),
    ]
