# Generated by Django 3.1.5 on 2021-03-25 06:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210325_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 6, 53, 42, 868811, tzinfo=utc)),
        ),
    ]
