# Generated by Django 3.1.5 on 2021-03-27 03:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210327_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 3, 50, 47, 330279, tzinfo=utc)),
        ),
    ]
