# Generated by Django 3.1.5 on 2021-03-27 10:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210327_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 10, 42, 39, 643509, tzinfo=utc)),
        ),
    ]
