# Generated by Django 3.1.5 on 2021-03-27 11:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20210327_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 11, 2, 16, 178295, tzinfo=utc)),
        ),
    ]
