# Generated by Django 3.1.5 on 2021-03-31 11:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20210327_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 11, 15, 57, 946761, tzinfo=utc)),
        ),
    ]
