# Generated by Django 3.1.5 on 2021-04-01 08:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20210331_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 8, 46, 7, 517409, tzinfo=utc)),
        ),
    ]
