# Generated by Django 3.1.5 on 2021-04-02 10:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20210401_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 10, 32, 0, 553232, tzinfo=utc)),
        ),
    ]
