# Generated by Django 3.1.5 on 2021-04-03 11:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20210402_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 11, 6, 5, 730413, tzinfo=utc)),
        ),
    ]
