# Generated by Django 3.1.5 on 2021-04-03 11:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20210403_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 11, 26, 49, 920149, tzinfo=utc)),
        ),
    ]
