# Generated by Django 3.1.5 on 2021-04-05 10:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20210403_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 5, 10, 28, 45, 197494, tzinfo=utc)),
        ),
    ]
