# Generated by Django 3.1.5 on 2021-04-06 07:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20210405_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 7, 20, 28, 250995, tzinfo=utc)),
        ),
    ]
