# Generated by Django 3.1.5 on 2021-01-28 14:53

import classroom.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='course',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='thumnails',
        ),
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='faculty_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_name',
        ),
        migrations.AddField(
            model_name='course',
            name='is_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='course_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classroom.category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default=classroom.models.generate_random_string, max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='classroom.Student'),
        ),
    ]
