# Generated by Django 3.1.5 on 2021-02-07 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('classroom', '0002_auto_20210128_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.faculty'),
        ),
        migrations.AlterField(
            model_name='course',
            name='notes',
            field=models.ManyToManyField(blank=True, to='classroom.Note'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, to='classroom.Student'),
        ),
        migrations.AlterField(
            model_name='course',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.subcategory'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_lectures',
            field=models.ManyToManyField(blank=True, to='classroom.Video_Lecture'),
        ),
    ]
