# Generated by Django 3.1.5 on 2021-02-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('classroom', '0003_auto_20210207_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default='<function generate_random_string at 0x7f472a605b80>', max_length=20),
        ),
    ]
