# Generated by Django 3.1.5 on 2021-02-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20210207_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='active',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='user',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='active',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='note',
            name='active',
        ),
        migrations.RemoveField(
            model_name='note',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='note',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='active',
        ),
        migrations.RemoveField(
            model_name='student',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='active',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='video_lecture',
            name='active',
        ),
        migrations.RemoveField(
            model_name='video_lecture',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='video_lecture',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='video_lecture',
            name='user',
        ),
    ]
