# Generated by Django 3.1.5 on 2021-02-13 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20210211_1637'),
        ('classroom', '0003_auto_20210207_0852'),
    ]

    operations = [
    ]
