# Generated by Django 3.1.5 on 2021-02-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('classroom', '0005_auto_20210213_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='name',
            field=models.CharField(blank=True, help_text='Name OF PDF File', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='video_lecture',
            name='name',
            field=models.CharField(blank=True, help_text='Add Name OF Video', max_length=20, null=True),
        ),
    ]
