# Generated by Django 3.1.5 on 2021-02-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_merge_20210213_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default='<function generate_random_string at 0x7f55a0beb820>', max_length=20),
        ),
    ]
