# Generated by Django 3.1.5 on 2021-02-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20210213_1425'),
        ('classroom', '0005_auto_20210211_1637'),
    ]

    operations = [
    ]
