# Generated by Django 3.1.5 on 2021-02-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20210215_1446'),
        ('classroom', '0007_auto_20210213_0910'),
    ]

    operations = [
    ]
