# Generated by Django 3.1.5 on 2021-02-21 16:06

import classroom.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0009_merge_20210218_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='is_save',
            field=models.ManyToManyField(blank=True, related_name='saves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default=classroom.models.generate_random_string, max_length=20),
        ),
    ]
