# Generated by Django 3.1.5 on 2021-02-27 16:34

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_videotesting'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='index',
            field=models.IntegerField(blank=True, help_text='For Chronological Order', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='index',
            field=models.IntegerField(blank=True, help_text='For Chronological Order', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='video_lecture',
            name='index',
            field=models.IntegerField(blank=True, help_text='For Chronological Order', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='video_lecture',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
