# Generated by Django 3.1.5 on 2021-02-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_auto_20210227_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video_lecture',
            old_name='video',
            new_name='video_url',
        ),
    ]
