# Generated by Django 3.1.5 on 2021-03-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_auto_20210227_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.CharField(default='Category Desc', max_length=100),
        ),
    ]
