# Generated by Django 3.1.5 on 2021-03-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0020_auto_20210325_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, help_text='This the slug field remain it empty', max_length=250, null=True, unique=True),
        ),
    ]
