# Generated by Django 3.1.5 on 2021-03-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0022_bidding_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding_amt',
            name='user',
            field=models.CharField(default='user1', max_length=100),
        ),
    ]
