# Generated by Django 3.1.5 on 2021-03-25 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0024_auto_20210325_0815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bidding_Amt',
        ),
    ]
