# Generated by Django 3.1.5 on 2021-03-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0025_delete_bidding_amt'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAskQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, help_text='For Chronological Order', null=True, unique=True)),
                ('question', models.CharField(blank=True, default='How long is this course duration', max_length=500, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
