# Generated by Django 3.1.5 on 2021-03-27 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0026_frequentlyaskquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
                ('phone_number', models.IntegerField(default='1234567890', validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('message', models.TextField(help_text='Type Your Message here')),
            ],
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='active',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='user',
        ),
        migrations.RemoveField(
            model_name='total_ratings',
            name='active',
        ),
        migrations.RemoveField(
            model_name='total_ratings',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='total_ratings',
            name='modified_date',
        ),
    ]
