# Generated by Django 3.1.5 on 2021-03-27 10:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0027_auto_20210327_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_of_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 27, 10, 53, 53, 732422, tzinfo=utc), null=True),
        ),
    ]
