# Generated by Django 3.1.5 on 2021-03-27 11:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0028_course_date_of_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_of_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 27, 11, 2, 16, 162854, tzinfo=utc), null=True),
        ),
    ]
