# Generated by Django 3.1.5 on 2021-03-31 11:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0031_auto_20210327_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='The Python Developer', max_length=200)),
                ('company_name', models.CharField(default='InternYuva', max_length=200)),
                ('role', models.CharField(default='Django Developer', max_length=200)),
                ('url', models.URLField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, default=datetime.date(2021, 3, 31), help_text='yyyy-mm-dd', null=True)),
                ('end_date', models.DateField(blank=True, default=datetime.date(2021, 5, 30), help_text='yyyy-mm-dd', null=True)),
                ('stipend', models.IntegerField(default=4000)),
                ('is_list', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='date_of_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 31, 11, 15, 57, 932105, tzinfo=utc), null=True),
        ),
    ]
