# Generated by Django 3.1.5 on 2021-04-01 08:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0032_auto_20210331_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipform',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_of_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 1, 8, 46, 7, 505274, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='internshipform',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 5, 31), help_text='yyyy-mm-dd', null=True),
        ),
        migrations.AlterField(
            model_name='internshipform',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 4, 1), help_text='yyyy-mm-dd', null=True),
        ),
    ]
