# Generated by Django 3.1.5 on 2021-04-02 10:32

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0033_auto_20210401_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='course_purchase', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_of_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 2, 10, 32, 0, 535134, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='internshipform',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 6, 1), help_text='yyyy-mm-dd', null=True),
        ),
        migrations.AlterField(
            model_name='internshipform',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 4, 2), help_text='yyyy-mm-dd', null=True),
        ),
    ]
