# Generated by Django 3.1.5 on 2021-04-03 11:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0034_auto_20210402_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='notes_thumbnail'),
        ),
        migrations.AddField(
            model_name='video_lecture',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='videos_thumbnail'),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_of_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 3, 11, 6, 5, 711823, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='internshipform',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 6, 2), help_text='yyyy-mm-dd', null=True),
        ),
        migrations.AlterField(
            model_name='internshipform',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 4, 3), help_text='yyyy-mm-dd', null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='document',
            field=models.FileField(upload_to='documents/<django.db.models.fields.CharField>/'),
        ),
    ]
