# Generated by Django 3.1.5 on 2021-04-03 11:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0035_auto_20210403_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='notes',
        ),
        migrations.AddField(
            model_name='course',
            name='notes_un',
            field=models.ManyToManyField(blank=True, help_text='Ignore It', related_name='course_notes_IgnoreIt', to='classroom.Notes'),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.course'),
        ),
        migrations.AddField(
            model_name='notes',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.course'),
        ),
        migrations.AddField(
            model_name='video_lecture',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_overview',
            field=models.ManyToManyField(blank=True, help_text='Ignore It', related_name='course_overview_IgnoreIt', to='classroom.CourseOverview'),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_of_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 3, 11, 26, 49, 908235, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_lectures',
            field=models.ManyToManyField(blank=True, help_text='Ignore It', related_name='video_lectures_IgnoreIt', to='classroom.Video_Lecture'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
